/*
 * Copyright 2017-2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.data.querydsl.suffix;

import org.springframework.data.querydsl.User;

import com.querydsl.core.types.dsl.EntityPathBase;

/**
 * Mimicks a class generated by Querydsl with a package suffix.
 *
 * @author Jens Schauder
 * @author Oliver Gierke
 * @see org.springframework.data.querydsl.SimpleEntityPathResolverUnitTests
 */
public class QUser extends EntityPathBase<User> {

	private static final long serialVersionUID = -2346766110501428367L;

	public static final QUser user = new QUser("user");

	public QUser(String user) {
		super(User.class, user);
	}
}
